Update ci.yml
temporary corrections for proper build output.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,13 +40,14 @@ jobs:
         continue-on-error: true #TODO: we currently continue as a warning!
         # `npm rebuild` will run all those post-install scripts for us.
         run: |
-          result=`npm rebuild && npm run prepare --if-present`
-          if $result ; then
-            # ensure it is a warning, rather than an error, as GH workflow does not support it!
-            echo '### :warning: issues encountered with `npm rebuild && npm run prepare`' >> $GITHUB_STEP_SUMMARY
-            exit 1 #TODO: in this case, we will still mandate the error!
-          fi
-          exit $result
+          npm rebuild && npm run prepare --if-present
+          # result=`npm rebuild && npm run prepare --if-present`
+          # if $result ; then
+          #   # ensure it is a warning, rather than an error, as GH workflow does not support it!
+          #   echo '### :warning: issues encountered with `npm rebuild && npm run prepare`' >> $GITHUB_STEP_SUMMARY
+          #   exit 1 #TODO: in this case, we will still mandate the error!
+          # fi
+          # exit $result
 
       - name: Run License check
         continue-on-error: true #TODO: we currently continue as a warning!
@@ -57,24 +58,26 @@ jobs:
       - name: Run outdated package check
         continue-on-error: true #TODO: we currently continue as a warning!
         run: |
-          result=`npm run check-package-outdated --if-present`
-          if $result ; then
-            # ensure it is a warning, rather than an error, as GH workflow does not support it!
-            echo '### :warning: Outdated packages detected!, check `npm run check-package-outdated`' >> $GITHUB_STEP_SUMMARY
-            exit 0 #TODO: we currently just ignore this error and raise it as a warning!
-          fi
-          exit $result
+          npm run check-package-outdated --if-present
+          # result=`npm run check-package-outdated --if-present`
+          # if $result ; then
+          #   # ensure it is a warning, rather than an error, as GH workflow does not support it!
+          echo '### :warning: Outdated packages detected!, check `npm run check-package-outdated`' >> $GITHUB_STEP_SUMMARY
+          #   exit 0 #TODO: we currently just ignore this error and raise it as a warning!
+          # fi
+          # exit $result
 
       - name: Run audit package check
         continue-on-error: true #TODO: we currently continue as a warning!
         run: |
-          result=`npm audit --dry-run --if-present`
-          if $result ; then
-          # ensure it is a warning, rather than an error, as GH workflow does not support it!
-            echo '### :warning: Package audit check failed!, check `npm audit`' >> $GITHUB_STEP_SUMMARY
-            exit 0 #TODO: we currently just ignore this error and raise it as a warning!
-          fi
-          exit $result
+          npm audit --dry-run --if-present
+          # result=`npm audit --dry-run --if-present`
+          # if $result ; then
+          # # ensure it is a warning, rather than an error, as GH workflow does not support it!
+          echo '### :warning: Package audit check failed!, check `npm audit`' >> $GITHUB_STEP_SUMMARY
+          #   exit 0 #TODO: we currently just ignore this error and raise it as a warning!
+          # fi
+          # exit $result
 
       - name: Run lint checks
         run: |
